package com.tree.community.model;

public class FollowAndFans {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow_and_fans.id
     *
     * @mbg.generated Tue Jun 30 23:42:30 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow_and_fans.from_user_id
     *
     * @mbg.generated Tue Jun 30 23:42:30 CST 2020
     */
    private Long fromUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow_and_fans.to_user_id
     *
     * @mbg.generated Tue Jun 30 23:42:30 CST 2020
     */
    private Long toUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow_and_fans.status
     *
     * @mbg.generated Tue Jun 30 23:42:30 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow_and_fans.gmt_create
     *
     * @mbg.generated Tue Jun 30 23:42:30 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow_and_fans.gmt_modified
     *
     * @mbg.generated Tue Jun 30 23:42:30 CST 2020
     */
    private Long gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow_and_fans.id
     *
     * @return the value of follow_and_fans.id
     *
     * @mbg.generated Tue Jun 30 23:42:30 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow_and_fans.id
     *
     * @param id the value for follow_and_fans.id
     *
     * @mbg.generated Tue Jun 30 23:42:30 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow_and_fans.from_user_id
     *
     * @return the value of follow_and_fans.from_user_id
     *
     * @mbg.generated Tue Jun 30 23:42:30 CST 2020
     */
    public Long getFromUserId() {
        return fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow_and_fans.from_user_id
     *
     * @param fromUserId the value for follow_and_fans.from_user_id
     *
     * @mbg.generated Tue Jun 30 23:42:30 CST 2020
     */
    public void setFromUserId(Long fromUserId) {
        this.fromUserId = fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow_and_fans.to_user_id
     *
     * @return the value of follow_and_fans.to_user_id
     *
     * @mbg.generated Tue Jun 30 23:42:30 CST 2020
     */
    public Long getToUserId() {
        return toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow_and_fans.to_user_id
     *
     * @param toUserId the value for follow_and_fans.to_user_id
     *
     * @mbg.generated Tue Jun 30 23:42:30 CST 2020
     */
    public void setToUserId(Long toUserId) {
        this.toUserId = toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow_and_fans.status
     *
     * @return the value of follow_and_fans.status
     *
     * @mbg.generated Tue Jun 30 23:42:30 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow_and_fans.status
     *
     * @param status the value for follow_and_fans.status
     *
     * @mbg.generated Tue Jun 30 23:42:30 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow_and_fans.gmt_create
     *
     * @return the value of follow_and_fans.gmt_create
     *
     * @mbg.generated Tue Jun 30 23:42:30 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow_and_fans.gmt_create
     *
     * @param gmtCreate the value for follow_and_fans.gmt_create
     *
     * @mbg.generated Tue Jun 30 23:42:30 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow_and_fans.gmt_modified
     *
     * @return the value of follow_and_fans.gmt_modified
     *
     * @mbg.generated Tue Jun 30 23:42:30 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow_and_fans.gmt_modified
     *
     * @param gmtModified the value for follow_and_fans.gmt_modified
     *
     * @mbg.generated Tue Jun 30 23:42:30 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }
}