package com.tree.community.model;

public class Province {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.id
     *
     * @mbg.generated Tue Jun 30 23:42:30 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.province_code
     *
     * @mbg.generated Tue Jun 30 23:42:30 CST 2020
     */
    private String provinceCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.name
     *
     * @mbg.generated Tue Jun 30 23:42:30 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.id
     *
     * @return the value of province.id
     *
     * @mbg.generated Tue Jun 30 23:42:30 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.id
     *
     * @param id the value for province.id
     *
     * @mbg.generated Tue Jun 30 23:42:30 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.province_code
     *
     * @return the value of province.province_code
     *
     * @mbg.generated Tue Jun 30 23:42:30 CST 2020
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.province_code
     *
     * @param provinceCode the value for province.province_code
     *
     * @mbg.generated Tue Jun 30 23:42:30 CST 2020
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.name
     *
     * @return the value of province.name
     *
     * @mbg.generated Tue Jun 30 23:42:30 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.name
     *
     * @param name the value for province.name
     *
     * @mbg.generated Tue Jun 30 23:42:30 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}