package com.tree.community.model;

public class Useroauths {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useroauths.id
     *
     * @mbg.generated Tue Jun 30 23:42:30 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useroauths.uid
     *
     * @mbg.generated Tue Jun 30 23:42:30 CST 2020
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useroauths.account_id
     *
     * @mbg.generated Tue Jun 30 23:42:30 CST 2020
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useroauths.type
     *
     * @mbg.generated Tue Jun 30 23:42:30 CST 2020
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useroauths.id
     *
     * @return the value of useroauths.id
     *
     * @mbg.generated Tue Jun 30 23:42:30 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useroauths.id
     *
     * @param id the value for useroauths.id
     *
     * @mbg.generated Tue Jun 30 23:42:30 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useroauths.uid
     *
     * @return the value of useroauths.uid
     *
     * @mbg.generated Tue Jun 30 23:42:30 CST 2020
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useroauths.uid
     *
     * @param uid the value for useroauths.uid
     *
     * @mbg.generated Tue Jun 30 23:42:30 CST 2020
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useroauths.account_id
     *
     * @return the value of useroauths.account_id
     *
     * @mbg.generated Tue Jun 30 23:42:30 CST 2020
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useroauths.account_id
     *
     * @param accountId the value for useroauths.account_id
     *
     * @mbg.generated Tue Jun 30 23:42:30 CST 2020
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useroauths.type
     *
     * @return the value of useroauths.type
     *
     * @mbg.generated Tue Jun 30 23:42:30 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useroauths.type
     *
     * @param type the value for useroauths.type
     *
     * @mbg.generated Tue Jun 30 23:42:30 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }
}