package com.tree.community.mapper;

import com.tree.community.model.BookMark;
import com.tree.community.model.BookMarkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface BookMarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_mark
     *
     * @mbg.generated Sun Jun 12 23:42:30 CST 2020
     */
    long countByExample(BookMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_mark
     *
     * @mbg.generated Sun Jun 12 23:42:30 CST 2020
     */
    int deleteByExample(BookMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_mark
     *
     * @mbg.generated Sun Jun 12 23:42:30 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_mark
     *
     * @mbg.generated Sun Jun 12 23:42:30 CST 2020
     */
    int insert(BookMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_mark
     *
     * @mbg.generated Sun Jun 12 23:42:30 CST 2020
     */
    int insertSelective(BookMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_mark
     *
     * @mbg.generated Sun Jun 12 23:42:30 CST 2020
     */
    List<BookMark> selectByExampleWithRowbounds(BookMarkExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_mark
     *
     * @mbg.generated Sun Jun 12 23:42:30 CST 2020
     */
    List<BookMark> selectByExample(BookMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_mark
     *
     * @mbg.generated Sun Jun 12 23:42:30 CST 2020
     */
    BookMark selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_mark
     *
     * @mbg.generated Sun Jun 12 23:42:30 CST 2020
     */
    int updateByExampleSelective(@Param("record") BookMark record, @Param("example") BookMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_mark
     *
     * @mbg.generated Sun Jun 12 23:42:30 CST 2020
     */
    int updateByExample(@Param("record") BookMark record, @Param("example") BookMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_mark
     *
     * @mbg.generated Sun Jun 12 23:42:30 CST 2020
     */
    int updateByPrimaryKeySelective(BookMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_mark
     *
     * @mbg.generated Sun Jun 12 23:42:30 CST 2020
     */
    int updateByPrimaryKey(BookMark record);
}